site_name: Cuadratura Gaussiana
theme:
  name: material

nav:
  - Introduccion: index.md
  - Cuadratura Gaussiana: explanation.md
  - Tutorial de uso: tutorials.md
  - Documentacion: reference.md

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths:
            - .
          options:
            show_root_heading: true
            show_source: false
            docstring_style: google

markdown_extensions:
- pymdownx.arithmatex:
    generic: true

extra_javascript:
- javascripts/mathjax.js
- https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
